import type { Metadata } from "next";
import { Italiana, Alata, Antic_Didone } from "next/font/google";
import "./globals.css";

const italiana = Italiana({
  subsets: ["latin"], // Specify the subsets you need
  weight: "400", // Specify the weight(s) needed (e.g., '400' for regular)
});

const alata = Alata({
  subsets: ["latin"], // Specify the subsets you need
  weight: "400", // Specify the weight(s) needed (e.g., '400' for regular)
});

const antic = Antic_Didone({
  subsets: ["latin"], // Specify the subsets you need
  weight: "400", // Specify the weight(s) needed (e.g., '400' for regular)
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${italiana.className} antialiased background-image-mobile lg:background-image lg:overflow-y-hidden`}>
        {children}
      </body>
      <div className={`${alata.className} ${antic.className}`}></div>
    </html>
  );
}
