import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Italiana } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const italiana = Italiana({
  subsets: ["latin"], // Specify the subsets you need
  weight: "400", // Specify the weight(s) needed (e.g., '400' for regular)
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${italiana.className} antialiased background-image`}>
        {children}
      </body>
    </html>
  );
}
